"""empty message

Revision ID: 0bba5d982e37
Revises: 900f39cf5a78
Create Date: 2025-10-03 17:33:33.889938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bba5d982e37'
down_revision = '900f39cf5a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('peso',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('color_cabello',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('color_piel',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('color_ojos',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('poblacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('diametro',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('diametro',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('poblacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('color_ojos',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('color_piel',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('color_cabello',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('peso',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('altura',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
