"""empty message

Revision ID: 382a7f84e611
Revises: a5cffa318ac2
Create Date: 2025-10-03 09:32:11.428595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a7f84e611'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('color_cabello', sa.String(length=30), nullable=False),
    sa.Column('color_piel', sa.String(length=30), nullable=False),
    sa.Column('color_ojos', sa.String(length=30), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
