"""empty message

Revision ID: 900f39cf5a78
Revises: f86496fb9c69
Create Date: 2025-10-03 16:45:46.202022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900f39cf5a78'
down_revision = 'f86496fb9c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False, server_default='SinNombre'))
        # batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False))
        # batch_op.create_unique_constraint(None, ['apellido'])
        # batch_op.create_unique_constraint(None, ['nombre'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_column('apellido')
        # batch_op.drop_column('nombre')
        pass

    # ### end Alembic commands ###
