"""empty message

Revision ID: c540086c9828
Revises: 382a7f84e611
Create Date: 2025-10-03 16:05:53.166184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c540086c9828'
down_revision = '382a7f84e611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito_personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planeta_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], name='favorito_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], name='favorito_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_pkey')
    )
    op.drop_table('favorito_planeta')
    op.drop_table('favorito_personaje')
    # ### end Alembic commands ###
