"""empty message

Revision ID: f86496fb9c69
Revises: c540086c9828
Create Date: 2025-10-03 16:08:59.156473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86496fb9c69'
down_revision = 'c540086c9828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito_planeta', schema=None) as batch_op:
        batch_op.drop_constraint('favorito_planeta_planeta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planeta', ['planeta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito_planeta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorito_planeta_planeta_id_fkey', 'personaje', ['planeta_id'], ['id'])

    # ### end Alembic commands ###
